name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: |
          go get .
          sudo apt-get install golang gcc libgl1-mesa-dev xorg-dev
      - name: Build
        run: go build -o linux_client -v ./...
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: linux_client
          asset_name: linux_client
          tag: ${{ github.ref }}
          overwrite: true
          body: "Release"
