name: Go

on: [push]

jobs:
  cross_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22.5' ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        run: |
          go get .
          sudo apt-get install golang gcc libgl1-mesa-dev xorg-dev

      - name: Get windows ck-client
        run: wget https://github.com/cbeuw/Cloak/releases/download/v2.9.0/ck-client-windows-386-v2.9.0.exe
      - name: Windows build
        run: |
          sudo apt-get install gcc-multilib
          sudo apt-get install gcc-mingw-w64
          GOOS=windows GOARCH=386 CGO_ENABLED=1 CXX=i686-w64-mingw32-g++ CC=i686-w64-mingw32-gcc go build -o dobby_client.exe
      - name: Make windows zip
        run: |
          mkdir windows_client
          mv ck-client-windows-386-v2.9.0.exe windows_client/ck-client.exe
          mv dobby_client.exe windows_client/client.exe
          zip -r windows_client.zip windows_client
      - name: Upload Windows client
        uses: actions/upload-artifact@master
        with:
          name: windows_client.zip
          path: .

      - name: Get linux ck-client
        run: |
          wget https://github.com/cbeuw/Cloak/releases/download/v2.9.0/ck-client-linux-amd64-v2.9.0
      - name: Linux build
        run: go build -o dobby_client -v ./...
      - name: Make linux zip
        run: |
          mkdir linux_client
          mv ck-client-linux-amd64-v2.9.0 linux_client/ck-client
          mv dobby_client linux_client/client
          zip -r linux_client.zip linux_client
      - name: Upload Linux client
        uses: actions/upload-artifact@master
        with:
          name: linux_client.zip
          path: .

  macos_build:
    runs-on: macos-latest
    strategy:
      matrix:
        go-version: [ '1.22.5' ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Get macos ck-client
        run: wget https://github.com/cbeuw/Cloak/releases/download/v2.9.0/ck-client-darwin-amd64-v2.9.0
      - name: MacOs build
        run:
          go build -o dobby_client ./...
      - name: Make macos zip
        run: |
          mkdir macos_client
          mv ck-client-darwin-amd64-v2.9.0 macos_client/ck-client
          mv dobby_client macos_client/client
          zip -r macos_client.zip macos_client
      - name: Upload MacOs client
        uses: actions/upload-artifact@master
        with:
          name: macos_client.zip
          path: .

  release:
    runs-on: ubuntu-latest
    needs: [cross_build, macos_build]

    steps:
      - name: Download linux client
        uses: actions/download-artifact@master
        with:
          name: linux_client.zip
          path: .
      - name: Download windows client
        uses: actions/download-artifact@master
        with:
          name: windows_client.zip
          path: .
      - name: Download macos client
        uses: actions/download-artifact@master
        with:
          name: macos_client.zip
          path: .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Linux
          release_name: Linux release
          draft: false
          prerelease: false

      - name: Upload Linux Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./linux_client.zip
          asset_name: linux_client.zip
          asset_content_type: application/zip

      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows_client.zip
          asset_name: windows_client.zip
          asset_content_type: application/zip