name: Generate release-artifacts

on:
    [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Windows build
        run: |
            ls
            pwd
            go build ./src/main.go
            
