name: Release APK

on: push

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Go
      uses: actions/setup-go@v5.0.1
      with:
        go-version: '1.22.4'

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Set up NDK
      id: setup_ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r26d
        link-to-sdk: true
        add-to-path: false

    - name: Build
      run: env GOOS=android CGO_ENABLED=1 go build ./...
